### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by Spacesky2022** [dyluc/roverimages#1]
Hello, how do I use it after I get the secret key? Thank you!

**Comment by dyluc** [comment]
You need to build the project using Gradle. The application plugin can build a distribution, use:

`./gradlew distZip`

Unzip the folder in build/distributions and the executable is in the /bin directory.

You can also pass the arguments directly to run with --args:

`./gradlew run --args="20 spirit ./images"`

**Comment by dyluc** [comment]
Replace 

`String apiKey = "DEMO_KEY"`

in Main.java with your API key.
